### ISSUE TITLE
KSUMMA checksum validation fails with filename as message

### ISSUE THREAD

**Issue by phlexss** [idstam/jsisie#15]
I found out that when the KSUMMA checksum validation fails it throws the following exception:

`Callbacks.CallbackException(new SieInvalidChecksumException(_fileName));`

It took me a while to find my file was failing the KSUMMA checksum because the error that was reported was just the filename.

Would it not be better to have something like:

`Callbacks.CallbackException(new SieInvalidChecksumException("KSUMMA invalid checksum!"));`

The file I used in this case has a lot of unbalanced vouchers so I enabled "Allow Unbalanced Voucher".....then I guess it makes sense that the KSUMMA checksum fails!? ....or should it maybe not fail when there are unbalanced vouchers and "Allow Unbalanced Voucher" is enabled? (as you maybe can tell I'm not a sie file expert ;-)

Thanks for the great work creating this library by the way!

Regards,
Ton.

**Comment by idstam** [comment]
KSUMMA is a CRC-32 checksum of the value content of the file, unbalanced vouchers doesn't affect that at all. 

The checksum algorithm only works for single bit character encodings witch is ok if you use the mandated codepage, but most files I've seen in the wild uses UTF-8 and ignores the checksum.

Since that is the only checksum that exists I thought the type name of the exception would be enough to separate it from other errors, but in hindsight I admit it was obvious only because I had spent several hours with the file specification at the time.

As it stands now I believe it would be too much of a breaking change  to alter that error message since there are companies running a lot of files through that code every day that uses that filename for error handling/reporting.
